# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Unit Test
      id: unit_test
      run: ./gradlew test -x jacocoTestReport

    - name: Publish Test Report Summary
      uses: mikepenz/action-junit-report@v2
      if: ${{ always() }}
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GIT_TOKEN }}

    - name: Deploy Test Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_dir: build/reports/tests/test
        destination_dir: junit

    - name: Test Code Coverage
      id: code_coverage
      run: ./gradlew jacocoTestReport jacocoTestCoverageVerification

    - name: Deploy Code Coverage Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        publish_dir: build/reports/jacoco/test/html
        destination_dir: jacoco
  
